Create displaying logic for ProjectManagerViewController
thesinisterfour/exam-project pull request #11
Opened 2023-04-27 09:42 UTC by jklaric

2023-04-27 19:16 UTC, LordStacker requested changes
changes to wich branch had the problem

2023-04-27 19:16 UTC, LordStacker commented on src/main/java/dk/easv/gui/controllers/ProjectManagerViewController.java
the problem was on login or this branch?

2023-04-28 10:25 UTC, patrikvalentiny approved these changes

2023-04-28 10:25 UTC, patrikvalentiny commented on src/main/java/dk/easv/gui/controllers/ControllerLogin.java
Remove this controller from this branch mange tak

2023-04-28 10:25 UTC, merged