Feature/admin view
thesinisterfour/exam-project pull request #6
Opened 2023-04-26 15:56 UTC by LeeVoi

Finished making the fxml and the controller for the admin main-view UI and controller

2023-04-26 20:08 UTC, patrikvalentiny commented
I will comment on this tomorrow but I feel like this is very much not on point of what I would want as an admin, a good start but I would change it up

2023-04-27 17:28 UTC, LeeVoi commented
worked on the logoutButton, fixed by Partik, this branch also contains the Admin-view FXML

2023-04-28 08:04 UTC, patrikvalentiny requested changes

2023-04-28 08:04 UTC, patrikvalentiny commented on src/main/java/dk/easv/Main.java
> +    private static Stage primaryStage;
no reason to have a static variable here

2023-04-28 08:04 UTC, patrikvalentiny commented on src/main/java/dk/easv/Main.java
> +    public static Stage getPrimaryStage() {
no need for this variable and method at all

2023-04-28 10:19 UTC, patrikvalentiny approved these changes

2023-04-28 10:19 UTC, merged